# action.yml
name: "Telegram Upload"
description: "Uploads files to a Telegram chat"
author: "PonomarevDA"

inputs:
  bot_token:
    description: "Telegram Bot Token"
    required: true
  chat_id:
    description: "Telegram Chat ID"
    required: true
  files:
    description: "One or more file paths or glob patterns (e.g. \"build/*.bin\" \"my_firmware.elf\")"
    required: true
  message:
    description: "Message to the last file"
    required: true
  add_git_info:
    description: "If true, then append info about the latest git commit and tag in the git repo."
    required: false
    default: "false"
  timeout:
    description: "Read request timeout. By default 30 seconds."
    required: false
    default: "30"

runs:
  using: docker
  image: Dockerfile
