# action.yml
name: "Telegram Upload"
description: "Uploads binaries (or any files) to a Telegram chat"
author: "PonomarevDA"

inputs:
  bot_token:
    description: "Telegram Bot Token"
    required: true
  chat_id:
    description: "Telegram Chat ID"
    required: true
  directory:
    description: "Directory with files to uplaod"
    required: true
  message: # todo
    description: "Message to the last file"
    required: true
  add_git_info: # todo
    description: "If true, then append info about the latest git commit and tag in the git repo."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: pip install requests
      shell: bash

    - name: Run deploy script
      run: |
        python scripts/deploy_files_to_telegram.py \
          --bot-token ${{ inputs.bot_token }} \
          --chat-id ${{ inputs.chat_id }} \
          --directory ${{ inputs.directory }} \
          --message ${{ inputs.message }} \
          --add-git-info ${{ inputs.add_git_info }}
      shell: bash
