# action.yml
name: "Telegram Upload"
description: "Uploads files to a Telegram chat"
author: "PonomarevDA"

inputs:
  bot_token:
    description: "Telegram Bot Token"
    required: true
  chat_id:
    description: "Telegram Chat ID"
    required: true
  files:
    description: "One or more file paths or glob patterns (e.g. \"build/*.bin\" \"my_firmware.elf\")"
    required: true
  message:
    description: "Message to the last file"
    required: true
  add_git_info:
    description: "If true, then append info about the latest git commit and tag in the git repo."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: pip install requests
      shell: bash

    - name: Run deploy script
      run: |
        python "${{ github.action_path }}/scripts/deploy.py" \
          --bot-token "${{ inputs.bot_token }}" \
          --chat-id "${{ inputs.chat_id }}" \
          --files "${{ inputs.files }}" \
          --message "${{ inputs.message }}" \
          --add-git-info "${{ inputs.add_git_info }}"
      shell: bash
