name: Tests
on: push

jobs:
  action:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to get tags

      - name: Create test files
        run: |
          mkdir -p build/release
          echo "Test" > build/release/test.bin

      - name: Run action (self-test)
        uses: ./.  # reference the action in the current repo
        with:
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          files: build/release/*.bin
          message: "Test from self-test workflow"
          add_git_info: "true"

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install and Run
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements-dev.txt
          pytest tests/*
