name: Test Action

on:
  push:
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # to get tags

      - name: Create test files
        run: |
          mkdir -p test_dir
          echo "Test" > test_dir/test.bin

      - name: Run action (self-test)
        uses: ./.  # reference the action in the current repo
        with:
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          files: test_dir/*.bin
          message: "Test from self-test workflow"
          add_git_info: "true"
